export const CITY = 'Chennai'

export const LOCATION_OPTIONS = {
  'North Chennai - Thiruvottiyur': { Thiruvottiyur: ['Kuppam Main Road', 'Ennore High Road', 'Sathuma Nagar Main Road', 'Theradi Street'], Kathivakkam: ['Kathivakkam High Road', 'Manali High Road', 'Basin Power Road'], Ernavur: ['Ernavur Main Road', 'Sathangadu Main Road'] },
  'North Chennai - Manali': { Manali: ['Manali High Road', 'CPCL Road', 'Sadayankuppam Road'], Mathur: ['Mathur MMDA Main Road', 'MFL Road', 'Periya Mathur Road'], 'Chinna Seemapuram': ['Seemapuram Main Road', 'Moolakadai Main Road'] },
  'North Chennai - Madhavaram': { Madhavaram: ['Madhavaram High Road', 'Madhavaram Milk Colony Road', 'GNT Road'], Puzhal: ['Puzhal Main Road', 'Puzhal Camp Road', 'Red Hills Road'], Moolakadai: ['Moolakadai Main Road', 'Madhavaram Red Hills Road'] },
  'North Chennai - Tondiarpet': { Tondiarpet: ['Tondiarpet High Road', 'Suryanarayana Street', 'Korukkupet Main Road'], Royapuram: ['Royapuram High Road', 'MG Road', 'Kalmandapam Road'], Washermenpet: ['Washing Street', 'Mannady Street', 'Mint Street'] },
  'North Chennai - Royapuram': { 'Old Washermenpet': ['Royapuram Bridge Road', 'Kalmandapam Road', 'Basin Power Road'], Pulianthope: ['Pulianthope High Road', 'Demellows Road', 'Strahans Road'], Perambur: ['Perambur High Road', 'Paper Mills Road', 'Madhavaram High Road'] },
  'Central Chennai - Thiru Vi Ka Nagar': { Peravallur: ['Perambur Red Hills Road', 'Paper Mills Road'], Kolathur: ['Kolathur Main Road', 'Retteri Junction Road', '200 Feet Road'], Villivakkam: ['Villivakkam Main Road', 'North Red Hills Road', 'MTH Road'] },
  'West Chennai - Ambattur': { Ambattur: ['Ambattur Red Hills Road', 'MTH Road', 'Ambattur Industrial Estate Road'], Korattur: ['Korattur Main Road', 'Railway Station Road', 'MTH Road'], Padi: ['Padi Lucas Road', 'MTH Road', 'Inner Ring Road'], Mogappair: ['Mogappair Main Road', 'Collector Nagar Main Road', 'Golden George Nagar Road'] },
  'Central Chennai - Anna Nagar': { 'Anna Nagar': ['2nd Avenue', 'Shanthi Colony', '12th Main Road', '5th Avenue', '18th Main Road'], Arumbakkam: ['Poonamallee High Road', 'MMDA Colony Main Road', 'Nelson Manickam Road'], Aminjikarai: ['Nelson Manickam Road', 'Pulla Avenue', 'P H Road'], 'Shenoy Nagar': ['Pulla Avenue', 'Shenoy Nagar Main Road', 'EVR Periyar Salai'] },
  'Central Chennai - Teynampet': { Teynampet: ['Anna Salai', 'Eldams Road', 'Teynampet Third Cross Street'], Nungambakkam: ['Nungambakkam High Road', 'College Road', 'Kodambakkam High Road'], 'Thousand Lights': ['Greams Road', 'Haddows Road', 'Cathedral Road'], Gopalapuram: ['Avvai Shanmugam Salai', 'Lloyds Road', 'Cenotaph Road'] },
  'West Chennai - Kodambakkam': { Kodambakkam: ['Arcot Road', 'Kodambakkam High Road', 'United India Colony Main Road'], Vadapalani: ['Arcot Road', '100 Feet Road', 'Jawaharlal Nehru Road'], Saligramam: ['Arcot Road', 'Saidapet Road', 'Kali Amman Koil Street'], 'Ashok Nagar': ['100 Feet Road', '12th Avenue', 'KK Nagar Main Road'] },
  'West Chennai - Valasaravakkam': { Valasaravakkam: ['Arcot Road', 'Alapakkam Main Road', 'Porur Road'], Alapakkam: ['Alapakkam Main Road', 'Maduravoyal Road', 'Porur Garden Road'], Porur: ['Mount Poonamallee Road', 'Porur Link Road', 'Manapakkam Main Road'] },
  'South Chennai - Alandur': { Alandur: ['Mount Poonamallee Road', 'GST Road', 'Alandur Road'], Adambakkam: ['Brindavan Nagar Main Road', 'Karuneegar Street', 'Velachery Main Road'], 'St Thomas Mount': ['GST Road', 'Meenambakkam Road', 'Mount Poonamallee Road'], Nanganallur: ['100 Feet Road', '5th Main Road', 'Jain Street'] },
  'South Chennai - Adyar': { Adyar: ['LB Road', 'Gandhi Road', 'Sardar Patel Road'], 'Besant Nagar': ['Elliots Beach Road', '7th Avenue', 'Kalakshetra Road'], Thiruvanmiyur: ['East Coast Road', 'LB Road', 'Taramani Road'], Guindy: ['Anna Salai', 'Guindy Industrial Estate Road', 'Sardar Patel Road'] },
  'South Chennai - Perungudi': { Perungudi: ['Old Mahabalipuram Road', 'Seevaram Main Road', 'Perungudi MRTS Road'], Velachery: ['100 Feet Road', 'Velachery Main Road', 'Taramani Link Road'], Taramani: ['Taramani Road', 'MGR Road', 'CSIR Road'], Pallikaranai: ['Pallikaranai Main Road', 'Medavakkam Main Road', 'Velachery Tambaram Road'] },
  'South Chennai - Sholinganallur': { Sholinganallur: ['Old Mahabalipuram Road', 'Sholinganallur Main Road', 'ECR Link Road'], Semmenchery: ['Semmenchery Main Road', 'Sathyabama University Road'], Neelankarai: ['East Coast Road', 'VGP Layout Main Road', 'Beach Road'], Injambakkam: ['East Coast Road', 'Muttukadu Road', 'Vettuvankeni Main Road'] },
  'South Chennai - Tambaram': { Tambaram: ['GST Road', 'Tambaram East Main Road', 'Tambaram West Railway Station Road', 'Mudichur Road', 'Velachery Tambaram Road'], Chromepet: ['GST Road', 'Radial Road', 'MIT Road', 'Chennai Bypass Road', 'Ragavendra Street'], Pallavaram: ['GST Road', 'Pallavaram-Thoraipakkam Road', 'Cantonment Road', 'Old Trunk Road'], Perungalathur: ['GST Road', 'Perungalathur Main Road', 'Mudichur Road', 'Vandalur Kelambakkam Road'], Mudichur: ['Mudichur Main Road', 'Tambaram Mudichur Road', 'Padmavathi Nagar Main Road'], Selaiyur: ['Velachery Tambaram Road', 'Camp Road', 'Bharathiyar Street'] },
  'South Chennai - Medavakkam': { Medavakkam: ['Medavakkam Main Road', 'Velachery Tambaram Road', 'Koot Road'], Shankarapuram: ['Shankarapuram Main Road', 'Medavakkam Koot Road'], Kovilambakkam: ['Kovilambakkam Main Road', 'Pallavaram Thoraipakkam Road'], Keelkattalai: ['Medavakkam Main Road', 'Keelkattalai Main Road', 'Kumaran Nagar Main Road'] },
}

export const ZONES = Object.keys(LOCATION_OPTIONS)

export const CITIES = Object.keys(LOCATION_OPTIONS)