export const CORPORATION = 'Greater Chennai Corporation'

export const LOCATION_OPTIONS = {
  'Zone 1 - Thiruvottiyur': { Thiruvottiyur: ['Kuppam Main Road', 'Ennore High Road', 'Sathuma Nagar Main Road'], Kathivakkam: ['Kathivakkam High Road', 'Manali High Road', 'Basin Power Road'], Ernavur: ['Ernavur Main Road', 'Sathangadu Main Road'] },
  'Zone 2 - Manali': { Manali: ['Manali High Road', 'CPCL Road', 'Sadayankuppam Road'], Mathur: ['Mathur MMDA Main Road', 'MFL Road', 'Periya Mathur Road'], 'Chinna Seemapuram': ['Seemapuram Main Road', 'Moolakadai Main Road'] },
  'Zone 3 - Madhavaram': { Madhavaram: ['Madhavaram High Road', 'Madhavaram Milk Colony Road', 'GNT Road'], Puzhal: ['Puzhal Main Road', 'Puzhal Camp Road', 'Red Hills Road'], Moolakadai: ['Moolakadai Main Road', 'Madhavaram Red Hills Road'] },
  'Zone 4 - Tondiarpet': { Tondiarpet: ['Tondiarpet High Road', 'Suryanarayana Street', 'Korukkupet Main Road'], Royapuram: ['Royapuram High Road', 'MG Road', 'Kalmandapam Road'], Washermenpet: ['Washing Street', 'Mannady Street', 'Mint Street'] },
  'Zone 5 - Royapuram': { 'Old Washermenpet': ['Royapuram Bridge Road', 'Kalmandapam Road', 'Basin Power Road'], Pulianthope: ['Pulianthope High Road', 'Demellows Road', 'Strahans Road'], Perambur: ['Perambur High Road', 'Paper Mills Road', 'Madhavaram High Road'] },
  'Zone 6 - Thiru Vi Ka Nagar': { Peravallur: ['Perambur Red Hills Road', 'Paper Mills Road'], Kolathur: ['Kolathur Main Road', 'Retteri Junction Road', '200 Feet Road'], Villivakkam: ['Villivakkam Main Road', 'North Red Hills Road', 'MTH Road'] },
  'Zone 7 - Ambattur': { Ambattur: ['Ambattur Red Hills Road', 'MTH Road', 'Ambattur Industrial Estate Road'], Korattur: ['Korattur Main Road', 'Railway Station Road', 'MTH Road'], Padi: ['Padi Lucas Road', 'MTH Road', 'Inner Ring Road'], Mogappair: ['Mogappair Main Road', 'Collector Nagar Main Road', 'Golden George Nagar Road'] },
  'Zone 8 - Anna Nagar': { 'Anna Nagar': ['2nd Avenue', 'Shanthi Colony', '12th Main Road'], Arumbakkam: ['Poonamallee High Road', 'MMDA Colony Main Road', 'Nelson Manickam Road'], Aminjikarai: ['Nelson Manickam Road', 'Pulla Avenue', 'P H Road'], 'Shenoy Nagar': ['Pulla Avenue', 'Shenoy Nagar Main Road', 'EVR Periyar Salai'] },
  'Zone 9 - Teynampet': { Teynampet: ['Anna Salai', 'Eldams Road', 'Teynampet Third Cross Street'], Nungambakkam: ['Nungambakkam High Road', 'College Road', 'Kodambakkam High Road'], 'Thousand Lights': ['Greams Road', 'Haddows Road', 'Cathedral Road'], Gopalapuram: ['Avvai Shanmugam Salai', 'Lloyds Road', 'Cenotaph Road'] },
  'Zone 10 - Kodambakkam': { Kodambakkam: ['Arcot Road', 'Kodambakkam High Road', 'United India Colony Main Road'], Vadapalani: ['Arcot Road', '100 Feet Road', 'Jawaharlal Nehru Road'], Saligramam: ['Arcot Road', 'Saidapet Road', 'Kali Amman Koil Street'], 'Ashok Nagar': ['100 Feet Road', '12th Avenue', 'KK Nagar Main Road'] },
  'Zone 11 - Valasaravakkam': { Valasaravakkam: ['Arcot Road', 'Alapakkam Main Road', 'Porur Road'], Alapakkam: ['Alapakkam Main Road', 'Maduravoyal Road', 'Porur Garden Road'], Porur: ['Mount Poonamallee Road', 'Porur Link Road', 'Manapakkam Main Road'] },
  'Zone 12 - Alandur': { Alandur: ['Mount Poonamallee Road', 'GST Road', 'Alandur Road'], Adambakkam: ['Brindavan Nagar Main Road', 'Karuneegar Street', 'Velachery Main Road'], 'St Thomas Mount': ['GST Road', 'Meenambakkam Road', 'Mount Poonamallee Road'], Nanganallur: ['100 Feet Road', '5th Main Road', 'Jain Street'] },
  'Zone 13 - Adyar': { Adyar: ['LB Road', 'Gandhi Road', 'Sardar Patel Road'], 'Besant Nagar': ['Elliots Beach Road', '7th Avenue', 'Kalakshetra Road'], Thiruvanmiyur: ['East Coast Road', 'LB Road', 'Taramani Road'], Guindy: ['Anna Salai', 'Guindy Industrial Estate Road', 'Sardar Patel Road'] },
  'Zone 14 - Perungudi': { Perungudi: ['Old Mahabalipuram Road', 'Seevaram Main Road', 'Perungudi MRTS Road'], Velachery: ['100 Feet Road', 'Velachery Main Road', 'Taramani Link Road'], Taramani: ['Taramani Road', 'MGR Road', 'CSIR Road'], Pallikaranai: ['Pallikaranai Main Road', 'Medavakkam Main Road', 'Velachery Tambaram Road'] },
  'Zone 15 - Sholinganallur': { Sholinganallur: ['Old Mahabalipuram Road', 'Sholinganallur Main Road', 'ECR Link Road'], Semmenchery: ['Semmenchery Main Road', 'Sathyabama University Road'], Neelankarai: ['East Coast Road', 'VGP Layout Main Road', 'Beach Road'], Injambakkam: ['East Coast Road', 'Muttukadu Road', 'Vettuvankeni Main Road'] },
}

export const ZONES = Object.keys(LOCATION_OPTIONS)

export const CITIES = Object.keys(LOCATION_OPTIONS)